# Generated by Django 4.2.6 on 2023-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_generalsetting_footer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('icerik', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.ImageField(default='', upload_to='moive_image')),
            ],
        ),
    ]
