# Generated by Django 4.2.6 on 2023-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('image', models.ImageField(upload_to='movie_image')),
                ('name', models.CharField(max_length=50)),
                ('sure', models.FloatField()),
            ],
        ),
    ]
