# Generated by Django 4.2.6 on 2023-11-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_indexmovie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
    ]
