# Generated by Django 4.2.6 on 2023-11-11 10:43

from django.db import migrations, models
import moviehunter.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexmovie',
            name='image',
            field=models.ImageField(storage=moviehunter.custom_storages.ImageSettingStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(storage=moviehunter.custom_storages.ImageSettingStorage, upload_to=''),
        ),
    ]
